name: equescodebelike
on:
  push:
    branches:
      - master
jobs:
  build:    
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
      - uses: subosito/flutter-action@v2
      - run: flutter build web --release --base-href /ciphers/
      - name: Copy assets
        run: |
          mkdir -p build/web/assets/symetric
          mkdir -p build/web/assets/assymetric
          cp -r assets/symetric/* build/web/assets/symetric/
          cp -r assets/assymetric/* build/web/assets/assymetric/
      - name: Deploy to GitHub Pages
        run: |
          cd build/web
          git init
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Automatic deployment by github-actions"
          git push https://${{ secrets.DEPLOY_TOKEN }}@github.com/${{ github.repository }}.git HEAD:gh-pages --force
